#!/bin/bash

# analyse_gpu_log.sh
# -------------------
# This script analyses GPU usage logs generated by `nvidia-smi` during a Slurm job.
# It is to be used with a logging line in your job script like:
#
#   nvidia-smi --query-gpu=index,timestamp,utilization.gpu,memory.total,memory.used,memory.free --format=csv -l 2 > gpu_stats_${SLURM_JOB_ID}.log &
#
# Then run this script at the end of the job:
#
#   ./analyse_gpu_log.sh gpu_stats_${SLURM_JOB_ID}.log
#
# It reports average and maximum GPU utilisation and memory usage (excluding the first sample).

if [ $# -ne 1 ]; then
  echo "Usage: $0 gpu_stats_LOGFILE"
  exit 1
fi

LOGFILE="$1"

echo
echo "Analysing GPU usage from: $LOGFILE"
echo

awk -F',' '
NR == 1 { next }        # skip header
NR == 2 { next }        # skip first data point (often pre-initialisation)

{
    gsub(/ %/, "", $3);
    gsub(/ MiB/, "", $5);
    gsub(/ MiB/, "", $6);

    idx = $1 + 0;  # ensure numeric index

    count[idx]++;
    util_sum[idx] += $3;
    util_max[idx]  = ($3 > util_max[idx] ? $3 : util_max[idx]);

    used_sum[idx] += $5;
    used_max[idx]  = ($5 > used_max[idx] ? $5 : used_max[idx]);

    free_sum[idx] += $6;
    free_max[idx]  = ($6 > free_max[idx] ? $6 : free_max[idx]);
}

END {
    for (i in count) {
        printf "====== GPU %d ======\n", i;

        printf "-- Utilisation --\n";
        printf "Average : %6.2f %%\n", util_sum[i] / count[i];
        printf "Max     : %6.2f %%\n\n", util_max[i];

        printf "-- Memory Used --\n";
        printf "Average : %6.0f MiB\n", used_sum[i] / count[i];
        printf "Max     : %6.0f MiB\n\n", used_max[i];

        printf "-- Memory Free --\n";
        printf "Average : %6.0f MiB\n", free_sum[i] / count[i];
        printf "Max     : %6.0f MiB\n", free_max[i];
        printf "\n";
    }
}' "$LOGFILE"

echo"For more detail see $LOGFILE"
